language: node_js
env:
  global:
    secure: DP1Q55umWk08gXkN+MbCWfvp7zykoycGdm0zAD5x/MXpw7lHJSzkzBPJD8mGHNwjOXBoYxTIkLmUyAXCs6SEzWu1LzGTfnnc3tpIxHU7kVxARuaa3FOp8+VteWHplFcR/cAfEXxO4JQHldSH+6CNJX+M2IwrfPBqTmG3bzIm+tFbveA4yMe4k6iMZtQVXOlh41qX+iwQreGy8JMSx44N3KvmFNTKXVeo0r0uqRHiHXnAFc1rvF9hIzGUC//AnnSe0vPR8+LKx/H8fWJJ++e7xtCJMKYCsLO8wwncZxd26hWWiWH2JV9c3GUOXO2Ynt+ZWnWhGcHfWcZBKwk/qH6h4qiIpArEUSC0b6VqcQFT8FsJe4ziXjkrStTAge4XYCHrK6G+hKqOH/O0P+ADQQLcSqzBsjgNNfyqTDyw+w6gcpEwrIZS3URZluMfD6CmtY7clPR6ipWC/ZkCbVUu8zicH6vwh6zrYPyVWmk/2bYVWGRirZEgOwF0zF04RYXu6YbL/WCM9O0f2ajBsv7kZjPG6t2ZD843fd1oBhrS8qs0bzw5VNtTjc3R/fApa8y+9NtJjOgt9SuUTduNrCLTmbbZqODCnUc3k4F/uFVD/3PeWWcZ4WodlqCHTzgH7KlGxrdCzaTc6abdtx4GY19et6hvsPsMcZbwDemqMkedlXsx1Jc=
deploy:
  provider: firebase
  token:
    secure: "DP1Q55umWk08gXkN"
  project: "scouting-compiler-dev"